#pragma once
#define NOXENGINE_FATAL_WINDOW_CREATE 0x01
#define NOXENGINE_SHADERS_MISSING 0x559
#define NOXENGINE_SHADERS_COMPILATION_ERROR 0x558
#define NOXENGINE_TEXTURE_LOAD_FAILED 0x304
#define NOXENGINE_MODEL_LOAD_ERROR 0x600
#define NOXENGINE_MODEL_PROCESSING_FILE_ERROR 0x601

#define GAME_NAME "NoxEngine"
#define GAME_VERSION "0.1"